# Generated by Django 2.2.7 on 2019-12-01 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 1, 17, 24, 8, 483118, tzinfo=utc), null=True),
        ),
    ]
